# Generated by Django 5.1.6 on 2025-02-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fluxocaixa',
            name='diferenca_quantidade',
        ),
        migrations.RemoveField(
            model_name='fluxocaixa',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='fluxocaixa',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='diferenca_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='valor_total_medicamentos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='valor_total_produtos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
