# Generated by Django 5.1.6 on 2025-02-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='funcionarios/')),
                ('nome', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcao', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fazenda', models.CharField(max_length=150)),
                ('localizacao', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Transferência', 'Transferência')], max_length=15)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produtor')),
            ],
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produtor')),
            ],
        ),
        migrations.CreateModel(
            name='Qualidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gordura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('proteina', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contagem_bacteriana', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], default='Aprovado', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('coleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.coleta')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produtor')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='vendas/')),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('quantidade_litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
    ]
