# Generated by Django 5.1.6 on 2025-02-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_medicamento_remove_fluxocaixa_diferenca_quantidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxocaixa',
            old_name='diferenca_valor',
            new_name='diferenca_medicamento',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade_final',
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='diferenca_produto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
