# Generated by Django 5.1.6 on 2025-02-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorista', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('destino', models.CharField(max_length=255)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_chegada', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Atraso', 'Atraso')], default='Em andamento', max_length=50)),
                ('motivo_atraso', models.TextField(blank=True, null=True)),
                ('feedback_cliente', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('coleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coleta')),
            ],
        ),
    ]
