# Generated by Django 5.1.6 on 2025-02-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_diferenca_medicamento_fluxocaixa_diferenca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxocaixa',
            old_name='diferenca',
            new_name='diferenca_medicamento',
        ),
        migrations.RenameField(
            model_name='fluxocaixa',
            old_name='valor_total',
            new_name='diferenca_produto',
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='valor_total_ativo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='valor_total_medicamentos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fluxocaixa',
            name='valor_total_produtos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
