# Generated by Django 5.1.6 on 2025-02-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_transporte_coleta'),
    ]

    operations = [
    ]
