# Generated by Django 5.1.6 on 2025-02-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250228_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transporte',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='data_chegada',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='data_envio',
        ),
        migrations.AlterField(
            model_name='transporte',
            name='coleta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='placa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluído', 'Concluído')], max_length=50),
        ),
    ]
