# Generated by Django 5.1.6 on 2025-02-28 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_transporte_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporte',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='data_chegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transporte',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transporte',
            name='coleta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='placa',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='transporte',
            name='status',
            field=models.CharField(choices=[('Em andamento', 'Em andamento'), ('Concluído', 'Concluído'), ('Atraso', 'Atraso')], default='Em andamento', max_length=50),
        ),
    ]
