# Generated by Django 5.1.6 on 2025-02-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_colaborador_ativo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='ativo',
            new_name='is_ativo',
        ),
    ]
