# Generated by Django 5.1.6 on 2025-02-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_transporte_data_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporte',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
