# Generated by Django 5.1.6 on 2025-02-19 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_coleta_fornecedor_pagamento_produtor_qualidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='data_venda',
        ),
        migrations.AddField(
            model_name='venda',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coleta',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
