# Generated by Django 5.1.6 on 2025-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_venda_data_venda_venda_data_alter_coleta_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('funcao', models.CharField(max_length=255)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total_ativo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total_produtos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total_medicamentos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('soma_produto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('diferenca_produto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('diferenca_medicamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_medicamento', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_inicial', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='qualidade',
            name='coleta',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='fornecedor',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='produtor',
        ),
        migrations.RemoveField(
            model_name='transporte',
            name='venda',
        ),
        migrations.DeleteModel(
            name='Coleta',
        ),
        migrations.DeleteModel(
            name='Qualidade',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
        migrations.DeleteModel(
            name='Produtor',
        ),
        migrations.DeleteModel(
            name='Transporte',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
