# Generated by Django 5.1.6 on 2025-02-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_coleta_fornecedor_pagamento_produtor_qualidade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transporte',
        ),
    ]
