# Generated by Django 5.1.6 on 2025-02-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_transporte'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedor',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='fornecedor',
            new_name='cliente',
        ),
    ]
