# Generated by Django 5.1.6 on 2025-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_fornecedor_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleta',
            name='data',
            field=models.DateField(),
        ),
    ]
