# Generated by Django 5.1.6 on 2025-02-20 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_produtor_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualidade',
            name='contagem_celulas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qualidade',
            name='produtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.produtor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qualidade',
            name='coleta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coleta'),
        ),
        migrations.AlterField(
            model_name='qualidade',
            name='gordura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qualidade',
            name='proteina',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qualidade',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
