# Generated by Django 5.1.6 on 2025-02-20 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_qualidade_contagem_celulas_qualidade_produtor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualidade',
            name='contagem_celulas',
        ),
        migrations.RemoveField(
            model_name='qualidade',
            name='produtor',
        ),
        migrations.AlterField(
            model_name='qualidade',
            name='coleta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.coleta'),
        ),
        migrations.AlterField(
            model_name='qualidade',
            name='gordura',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='qualidade',
            name='proteina',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='qualidade',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=10),
        ),
    ]
