# Generated by Django 5.1.6 on 2025-02-20 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_qualidade_contagem_celulas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualidade',
            name='status',
        ),
    ]
