# Generated by Django 5.1.6 on 2025-02-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_qualidade_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualidade',
            name='ativo',
        ),
        migrations.AddField(
            model_name='qualidade',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
