# Generated by Django 5.1.6 on 2025-02-20 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_qualidade_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualidade',
            name='produtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.produtor'),
            preserve_default=False,
        ),
    ]
