# Generated by Django 5.1.6 on 2025-02-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_qualidade_produtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualidade',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=50),
        ),
    ]
