# Generated by Django 5.1.6 on 2025-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_venda_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='vendas/'),
        ),
    ]
