# Generated by Django 5.1.6 on 2025-02-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_caixa_delete_fluxocaixa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caixa',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
